language: c
sudo: required

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: clang
      env:
       - MY_OS=trusty
       - INKSCAPE=inkscape
    - os: linux
      dist: precise
      compiler: gcc
      env:
       - MY_OS=precise
       - INKSCAPE=true
    - os: osx
      env:
       - MY_OS=macos
       - INKSCAPE=true

addons:
 apt:
  packages:
   - autoconf
   - autotools-dev
   - automake
   - bison
   - docbook
   - docbook-xml
   - docbook-xsl
   - gcc
   - libgnutls-dev
   - libhiredis-dev
   - libicu-dev
   - libmemcached-dev
   - libreadline-dev
   - libtool
   - libwrap0-dev
   - libxslt1-dev
   - make
   - pkg-config
   - tcl8.5
   - xsltproc
   - libboost-dev
   - libboost-system-dev
   - libboost-thread-dev
   - libboost-test-dev
   - libboost-regex-dev
   - inkscape

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install yazpp; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./travis/travis-init.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -yq libyaz5-dev libyazpp6-dev; fi

before_script:
 - ./buildconf.sh

script:
 - ./configure
 - make INKSCAPE=${INKSCAPE} -j3
 - if [[ "$SKIP_CHECK" != "true" ]]; then make INKSCAPE=${INKSCAPE} check; fi

